all:
	@(cd tools; $(MAKE))
	@(cd barber; $(MAKE))
	@(cd messages; $(MAKE))
	@(cd protocol; $(MAKE))
	@(cd shmemory; $(MAKE))
	@(cd semaphores; $(MAKE))

clean:
	@(cd tools; $(MAKE) clean)
	@(cd barber; $(MAKE) clean)
	@(cd messages; $(MAKE) clean)
	@(cd protocol; $(MAKE) clean)
	@(cd shmemory; $(MAKE) clean)
	@(cd semaphores; $(MAKE) clean)
